### ISSUE TITLE
Button Class is not working for me

### ISSUE THREAD

**Issue by ServusJon** [philipmadeley/framerJS-snippets#1]
Any idea? 
![bildschirmfoto 2016-05-31 um 13 57 58](https://cloud.githubusercontent.com/assets/783416/15673543/bbc0f934-2737-11e6-872d-852480432e3d.png)

**Comment by philipmadeley** [comment]
I'm pretty busy, but let me take a look at this next week. Or maybe post up in the Framer Facebook community :)

**Comment by philipmadeley** [comment]
Servus, 
Sorry it took a while for me to get back to you. 
Take a look at this example:  http://share.framerjs.com/28g9yg8ghiod/
Without looking at your file I cannot work out your error. I suspect it might be something to do with the name of your module file. 
Let me know how you get on :)
